package com.mentalhealthforum.mentalhealthforum_backend.config.enumConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.ProfileVisibility;

public class ProfileVisibilityWritingConverter extends AbstractPostgresEnumWritingConverter<ProfileVisibility>{}