package com.mentalhealthforum.mentalhealthforum_backend.config.enumConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.SupportRole;

public class SupportRoleWritingConverter extends AbstractPostgresEnumWritingConverter<SupportRole>{}