package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.ConnectionStatus;

public class ConnectionStatusWritingConverter extends AbstractPostgresEnumWritingConverter<ConnectionStatus>{}