package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.ContentWarningType;

public class ContentWarningTypeWritingConverter extends AbstractPostgresEnumWritingConverter<ContentWarningType>{}