package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.OtpPurpose;

public class OtpPurposeWritingConverter extends AbstractPostgresEnumWritingConverter<OtpPurpose>{}