package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.ProfileVisibility;

public class ProfileVisibilityWritingConverter extends AbstractPostgresEnumWritingConverter<ProfileVisibility>{}