package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.RestrictionType;

public class RestrictionTypeWritingConverter extends AbstractPostgresEnumWritingConverter<RestrictionType>{}