package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.WarningType;

public class WarningTypeWritingConverter extends AbstractPostgresEnumWritingConverter<WarningType>{}